### PR TITLE
Updated magisk_patched_boot_11.0.4.1.img file

### PR DESCRIPTION
**Pull request by octoshrimpy**
Compressed with 7zip, because it was 96MB in size, Github's max filesize is 25MB.
Used global 7t variant, OOS 11.0.4.1.

### CODE REVIEW

**Comment by Raymo111** [comment]
I'm not accepting ROM updates.

**Comment by octoshrimpy** [comment]
Okay. This is one of the first hits across multiple search indexers for rooting a 7T. Will it not fail if someone without experience attempts to follow instructions due to the older boot.img?

**Comment by Raymo111** [comment]
Can they not just upgrade to the latest OOS immediately after?

**Comment by octoshrimpy** [comment]
There may have been something wrong with my setup last time I attempted, but back in 11.0.1(?)  it didn't let me downgrade the boot.img. I'll try again with a test phone that is sitting on 11.4.

**Comment by Raymo111** [comment]
Sounds good, if it doesn't work I'll add your OOS11 image to the repo.

**Pull request closed without merging**
